workspace:
  base: /drone/src
  path: bean-auto-utils

pipeline:
  build:
    image: ${JDK_VERSION}
    pull: true
    commands:
#      - mkdir /root/.m2
#      - cp /drone/src/rapidpm-dependencies/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn clean
      - mvn test

  deploy:
    image: ${JDK_VERSION}
    pull: true
    commands:
#      - mkdir /root/.m2
#      - cp /drone/src/rapidpm-dependencies/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn clean
#      - mvn deploy
    when:
        matrix:
          JDK_VERSION: svenruppert/maven-3.5-jdk-08:latest
        branches:
          include: develop, release/*, master
          exclude: feature/*


matrix:
  JDK_VERSION:
  - maven:3.5-jdk-8-alpine
  - svenruppert/maven-3.5-jdk-08
  - svenruppert/maven-3.5-jdk-09
  - svenruppert/maven-3.5-jdk-10
  - svenruppert/maven-3.5-jdk-oracle-09
  - svenruppert/maven-3.5-jdk-zulu-08
  - svenruppert/maven-3.5-jdk-zulu-09
  - maven:3.5-ibmjava-8-alpine
  - maven:3.5-ibmjava-9-alpine

